export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAIL = "GET_NOTES_FAIL";
export const GET_NOTES_RESET = "GET_NOTES_RESET";

export const GET_NOTE_REQUEST = "GET_NOTE_REQUEST";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const GET_NOTE_FAIL = "GET_NOTE_FAIL";
export const GET_NOTE_RESET = "GET_NOTE_RESET";
